// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"log_demo/biz/dal"
)

func main() {
	dal.Init()
	h := server.Default()

	register(h)
	h.Spin()
}
